### ISSUE TITLE
Runtime Warning in the Leap IDE

### ISSUE THREAD

**Issue by akoszegi** [dwave-examples/job-shop-scheduling#1]
When the demo is run in the Leap IDE there's runtime warning. 
![image](https://user-images.githubusercontent.com/15724694/77971946-e9be7e80-72a4-11ea-8015-70937b430bae.png)

**Comment by seatim** [comment]
This issue no longer reproduces.  Here is a screenshot of current state.
<img width="1183" alt="Screen Shot 2021-03-16 at 4 52 00 PM" src="https://user-images.githubusercontent.com/22515416/111394704-7dd15380-8678-11eb-8319-b4ac090e1e19.png">

Recommend closing this issue as the warning no longer appears.

Note, the problem bqm is now printed where the warning used to appear.  That may not be ideal as it appears to be a bit of debug code and its size distracts from the smaller results text.  But that is a separate issue.

**Comment by hhtong** [comment]
Agreed, I've just removed the print statement in #12
