### ISSUE TITLE
Missing modules!

### ISSUE THREAD

**Issue by AlkisPis** [dwave-examples/job-shop-scheduling#15]
Re: demo py

    from dwave.system.composites import EmbeddingComposite
    from dwave.system.samplers import DWaveSampler

Missing from the package. Not even a comment about where one can find them!

👎

**Comment by randomir** [comment]
Indeed, README of this example is lacking instructions on how to install requirements:
```
pip install -r requirements.txt
```

We'll fix it. Thanks for reporting.
